name: Release

# Trigger on merge to main
on:
  release:
    types: [published]

# Job Definition
jobs:
  Release:
    # run mvn package for ubuntu

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Build Jar
        run: mvn package

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: "*.jar"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}